version: 1.8.14.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
image: Visual Studio 2017
shallow_clone: true
install:
- ps: Invoke-Expression "./bootstrap.ps1"
build_script:
- ps: >-
    $dev = $false

    $genArtifacts = (!$Env:APPVEYOR_PULL_REQUEST_NUMBER)

    ./build-scripts/full.ps1 -version $Env:APPVEYOR_BUILD_VERSION -generateArtifacts $genArtifacts -dev $dev

    if (!$dev -and (Test-Path ./builds)) {
      Copy-Item ./builds/*/* .
    }
test:
  categories:
    except:
    - Web
artifacts:
- path: dev-builds/*/*
  name: dev
- path: builds/*/HDT-Installer.exe
  name: prod-squirrel
- path: builds/*/*.nupkg
  name: prod-squirrel
- path: builds/*/RELEASES
  name: prod-squirrel
- path: builds/*/Hearthstone.Deck.Tracker-*.zip
  name: prod-portable
- path: HDT-Installer.exe
  name: prod-asia
- path: '*.nupkg'
  name: prod-asia
- path: RELEASES
  name: prod-asia
- path: Hearthstone.Deck.Tracker-*.zip
  name: prod-asia
deploy: off